### ISSUE TITLE
Items missing proper attachment slots 

### ISSUE THREAD

**Issue by alexglitch** [aimnas/core#14]
Item No - Item Name - Description (if necessary):
2623 - Beret, Red - Other berets have tags to mount NVGs and camo scarves
2671 - FAST Helm - The heavier FASTM Helms have proper tags
2672 - FAST C18 - ditto
2673 - FAST C20 - ditto
2677 - FAST desert - ditto
2678 - FAST D C18 - Ironically the C20 version is properly tagged 
4329 - ST CPW 9 Collapsed - The extended version is properly tagged 
4368 - ST CPW 5-7 Collapsed - ditto
4376 - ST CPW 4.6 Collapsed - ditto
4465 - SIG MPXS 9 - The MPX 9 is properly tagged
4466 - SIG MPXS 9 Collapsed - ditto
4584 - Ingram M6
5292 - XM29 OICW - missing image? pops up as NADA for me 
5472 - Type 87
5473 - Type 87-1 - The Collapsed version (5474) is properly tagged 
That's about it for now.

**Comment by alexglitch** [comment]
New stuff: 
The Bolo and C96 Mausers in 7.62x25mm is actually in 7.63mm Mauser for some reason, and the Bolo Mauser in both 7.62 and 7.63 Mauser is not properly tagged for Attachments

**Comment by smeag** [comment]
All reported issues fixed. Thanks.
