### ISSUE TITLE
Can't put mercenaries on the map, having to use "spread" option

### ISSUE THREAD

**Issue by Carl-Robert** [aimnas/core#6]
Hey!

Changed recently from 1.13 SVN to AIMNAS, and seems I'm unable to place any mercenaries on the sector-map when traveling to it, only the automatic "spread" option lets me play the sector. 
There is no "highlighted area" showing, hence not possible to put any mercenaries on the map, as would always complain about it.
Maybe something 1.13 changed? I remember there being one note about preventing mercs to be put on the edges of the map where they would be invisible, maybe not working together with big maps? Or just a weird issue I'm alone with?

Newest 1.13 build and newest AIMNAS by the time of writing 4.6.2017.

**Comment by DepressivesBrot** [comment]
Use the arrow keys to move the map screen or play on a higher resolution (1650+ supports the full map at once)

**Comment by Carl-Robert** [comment]
Oh! Figured there had to be a way, otherwise would have been reported before. So arrow keys it is, given that the UI doesn't scale too well. 

Thanks for the brief response!
