### ISSUE TITLE
BR's descriptions too long and other issues

### ISSUE THREAD

**Issue by tais** [aimnas/core#7]
****AUG-A1 - has Styer instead of Steyr in description, also not named Steyr AUG-A1 which makes it show up in the wrong location (others named Steyr AUG-A2)** 

**Texts too long**

**- QSW-06 (opposed to the... )**
- Walther PPK (last word, firearms)
- Magpul FMG9 (than metal. making it....)
- QCW-05 (as the People's.....)
- Nemo Omen ASP (carbine with hard hitting....)
- Sako 85 Finnlight (cheek piece...)
- Springfield M1903 (M1 rifles to arm all...)
- Winchester 1895 Russian (bolt-action rifle..., also MosinANagant text error)**

**all fixed**

**Comment by tais** [comment]
**Ammo texts too long**

- Box .300 AAC BLK AP (current standard 9mm submachine...)
- Box .380 ACP [Standard, AP, Glaser, HP] (defense.)
- Box 6.5 Arisaka (cartridge.)
- Box 9x19mm 7N21 (jacket.)

**Comment by tais** [comment]
Armour

Bandana should not be for sale

Misc
Bayonet - K98 (is fairly thick when....)
Traumapack (to create pressure on...)
A. Reflex Sight, C-More (acquisition in existence.)
Food Box - Datrex Calorie Bars (box contains 8 rations)

**Comment by tais** [comment]
Trench Coat is for sale in BR's

**Comment by smeag** [comment]
K, all fixed now.
